### ISSUE TITLE
Tap Detection on Fish

### ISSUE THREAD

**Issue by syedshahzebhasnain** [InteractiveAquariumOTN/InteractiveAquarium#25]

**Comment by archie10** [comment]
I have made the snippet just needs to integrate the it in the code. Currently trying to understand the code. will complete this task latest by tomorrow.

**Comment by syedshahzebhasnain** [comment]
Wheres the code?

**Comment by Abhikalra** [comment]
akshay,you have paused the animation but we also need the coordinates of the fish so that the popup table can be opened adjacent to it...You and deepinder need to coordinate with each other to firstly, obtain the position of the fish that is paused,create a pop up adjacent to the fish  and thereafter deepinder will create a table and populate it with data within the pop up

**Comment by sidhudeepinder** [comment]
@Abhikalra I have done this part!

**Comment by Abhikalra** [comment]
Deepinder...pausing of fish animation on click is done..akshay is probably working on retrieving the x and y coord of the fish when it is paused.This will be needed to open a popup adjacent to the fish..This popup will be the table which shows the fish information ..Once this is done, you would have to populate the data into the table..You can choose the best method you see for creating this table on the html page...it can be static or SQLite or using web service from a hosted DB or any other (whatever gets the job done)..ps: skeleton for a simple table included in html file already

**Comment by sidhudeepinder** [comment]
@archie10 @Abhikalra   I've done that part, retrieving x and y co-ordinates.
