### ISSUE TITLE
Populating Active Content on Tap

### ISSUE THREAD

**Issue by syedshahzebhasnain** [InteractiveAquariumOTN/InteractiveAquarium#34]
Populating the wire frame based data onto the tabs and items.

**Comment by sidhudeepinder** [comment]
The on-click pop-up is working!

**Comment by sidhudeepinder** [comment]
Now working on populating the wireframe.
I hope it will be done by tomorrow.

**Comment by sidhudeepinder** [comment]
@syedshahzebhasnain  do we need picture of fish on the pop-up?

**Comment by sidhudeepinder** [comment]
Please have a look at the code, I have made certain changes like:
- added interactive event listener to display the pop-up menu;
- implemented basic functions that displays the image in the pop-up and certain information;
- for populating the table on the pop-up, I just loaded data into the web page itself, because we are not using any back-end;
- the buttons for "video" and "world movement" are added but do not display any data;
